### ISSUE TITLE
The ability to lift a meta

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#352]
This means 3 things:

0. [x] Lift a meta
1. [x] Unlift the solution
2. [ ] Report error when unlifted to negative
3. [ ] Support spines with lifted variables

**Comment by ice1000** [comment]
I misunderstood the feature. Superseded by #440
