### ISSUE TITLE
Turn `I`, `left`, `right` into keywords

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#376]
Reasons:

+ They are crucial to the type theory
+ Their types are simple enough. The ability to write down `prim arcoe : blabla` makes the theory easier to understand (if it's a keyword, you may forget about its type signature, like which parameter is implicit, etc.), but for `I`, `left`, `right` they're too simple
+ My upcoming core type theory refactoring can be simplified drastically using this
+ `left` and `right` are also used as patterns. By making them keywords we no longer need prim states in pattern checker.

**Comment by imkiva** [comment]
I agree. Then let's do it in #256

**Comment by imkiva** [comment]
So we can also simplify lots of code in #256

**Comment by ice1000** [comment]
> So we can also simplify lots of code in #256

Great!!

**Comment by dark-flames** [comment]
## Tasks

- [ ] Make `I ` into a keyword.
- [ ] Resove 0/1 into left/right when typed as` I`.
- [ ] Update tests.
- [ ] Remove prim state.

**Comment by ice1000** [comment]
@dark-flames are you sure about removing prim state? `arcoe` will still be prim (and in the future, `hcomp` and `Glue`)

**Comment by dark-flames** [comment]
Well, so change it to "Remove the `I`, `right`,  `left ` in the prim factory"?

**Comment by ice1000** [comment]
@dark-flames Yes
